name: abrtictactoe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  ###--- utils, services, preference ---###
  async: ^2.11.0
  logging: ^1.2.0
  shared_preferences: ^2.2.3
  audioplayers: ^6.0.0
  go_router: ^14.0.2
  ###--- state management ---###
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/
  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: OpenSans Light
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
